# Generated by Django 5.2.6 on 2025-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_date_shipped_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='consumer_studies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ideal_for',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='what_makes_it_potent',
            field=models.TextField(blank=True),
        ),
    ]
