# Generated by Django 5.2.5 on 2025-11-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
