# Generated by Django 5.2.5 on 2025-11-15 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_category_hover_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Enter discount percentage (e.g., 10 for 10%)')),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=datetime.datetime.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
