# Generated by Django 5.2.6 on 2025-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_comboreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
        migrations.DeleteModel(
            name='ComboReview',
        ),
    ]
