# Generated by Django 5.2.6 on 2025-12-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_product_rating_delete_comboreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
